#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 18 14:53:00 2020

@author: fatih
"""
import locale
import os
import re
import subprocess
import sys
from datetime import datetime
from locale import gettext as _
from pathlib import Path
from shutil import rmtree

from aptsources import sourceslist as aptsourceslist

locale.bindtextdomain('pardus-update', '/usr/share/locale')
locale.textdomain('pardus-update')


def main():
    def subupdate():
        subprocess.call(["apt", "update"],
                        env={**os.environ, 'DEBIAN_FRONTEND': 'noninteractive'})

    def aptclean():
        subprocess.call(["apt", "clean"],
                        env={**os.environ, 'DEBIAN_FRONTEND': 'noninteractive'})

    def dpkgconfigure():
        subprocess.call(["dpkg", "--configure", "-a"],
                        env={**os.environ, 'DEBIAN_FRONTEND': 'noninteractive'})

    def fixbroken():
        subprocess.call(["apt", "install", "--fix-broken", "-yq"],
                        env={**os.environ, 'DEBIAN_FRONTEND': 'noninteractive'})

    def set_source_state(state, line, file_path):

        if state not in ("0", "1"):
            print("Invalid state parameter.", file=sys.stderr)
            sys.exit(1)

        print("{}\n\nold: {}\n".format(file_path, line))
        sources = aptsourceslist.SourcesList()
        for source in sources.list:
            try:
                if source.line.strip() == line and source.file == file_path:
                    source.set_enabled(state == "1")
                    print("new: {}\n".format(source.line.strip()))
                    break
            except Exception as e:
                print("{}".format(e))
                continue
        sources.save()

        print(_("Package Manager Cache is updating, please wait..."))
        print("")
        subupdate()

    def fix_sources(slist_content, fix_slistd, slistd_remove, configure_state, fixbroken_state):

        allowed_flags = {"0", "1"}
        if not (fix_slistd in allowed_flags and slistd_remove in allowed_flags and
                configure_state in allowed_flags and fixbroken_state in allowed_flags):
            print("Invalid state flags provided. Aborting.", file=sys.stderr)
            sys.exit(1)

        if not is_safe_sources(slist_content):
            print("Malicious apt source detected. Execution aborted.", file=sys.stderr)
            sys.exit(1)

        print("{}:\n\n{}".format(_("New Sources List"), slist_content))
        print("{}: {}\n".format(_("Fix sources.list.d"), fix_slistd))
        if fix_slistd == "1":
            print("{}: {}\n".format(_("Sources List Dir Remove"), slistd_remove))
        print("{}: {}\n".format(_("DPKG Configure State"), configure_state))
        print("{}: {}\n".format(_("Fix Broken State"), fixbroken_state))

        if fix_slistd == "1":
            sourceslistd_dir = "/etc/apt/sources.list.d"
            if os.path.isdir(sourceslistd_dir):
                if slistd_remove == "0":
                    sources = aptsourceslist.SourcesList()
                    for source in sources.list:
                        try:
                            source.set_enabled(False)
                        except Exception as e:
                            print("{}".format(e))
                            continue
                    sources.save()
                elif slistd_remove == "1":
                    try:
                        rmtree(sourceslistd_dir, ignore_errors=True)
                        Path(sourceslistd_dir).mkdir(parents=True, exist_ok=True)
                    except Exception as e:
                        print("{}".format(e))
        else:
            print(_("sources.list.d fix skipped per user request."))

        sources_list_file = open("/etc/apt/sources.list", "w")
        sources_list_file.write("{}\n### This section generated by Pardus Update at {} ###\n".format(
            slist_content, str(datetime.now())))
        sources_list_file.flush()
        sources_list_file.close()

        rmtree("/var/lib/apt/lists/", ignore_errors=True)
        aptclean()
        print(_("Package Manager Cache is updating, please wait..."))
        print("")
        subupdate()

        if configure_state == "1":
            dpkgconfigure()
        else:
            print(_("dpkgconfigure skipped per user request."))

        if fixbroken_state == "1":
            fixbroken()
        else:
            print(_("fixbroken skipped per user request."))

    def is_safe_sources(sources_text):
        if not sources_text or not str(sources_text).strip():
            return False

        allowed_signed_by_prefixes = (
            "/usr/share/keyrings/",
            "/etc/apt/keyrings/",
        )

        for raw_line in str(sources_text).splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue

            m = re.match(r"^deb(-src)?\s+(?:\[(.*?)\]\s+)?([^\s]+)", line)
            if not m:
                return False

            options = m.group(2)
            uri = m.group(3).lower()

            if not (uri.startswith("http://") or uri.startswith("https://")):
                return False

            if options:
                for token in options.replace(",", " ").split():
                    if "=" in token:
                        key, value = token.split("=", 1)
                    else:
                        key, value = token, ""
                    key = key.lower()
                    value_l = value.lower()

                    if key == "trusted":
                        return False
                    if key.startswith("allow-insecure") or key.startswith("allow-weak") or key.startswith("allow-downgrade"):
                        return False
                    if key in ("check-valid-until", "check-date"):
                        if value_l in ("false", "no", "0", "off", "disable", "disabled"):
                            return False
                        continue
                    if key == "signed-by":
                        path = os.path.normpath(value)
                        if ".." in path.split(os.sep):
                            return False
                        if not any(path.startswith(prefix) for prefix in allowed_signed_by_prefixes):
                            return False

            compact_line = line.lower().replace(" ", "")
            for scheme in ("file:", "copy:", "cdrom:"):
                if scheme in compact_line:
                    return False

        return True

    if len(sys.argv) > 1:
        if sys.argv[1] == "setsourcestate":
            set_source_state(sys.argv[2], sys.argv[3], sys.argv[4])
        elif sys.argv[1] == "fixsources":
            fix_sources(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6])
        else:
            print("unknown argument error")
    else:
        print("no argument passed")


if __name__ == "__main__":
    main()
